import type { RawSourceItemDetail } from "@/server/sources/source.types";

type DemoSeedItem = RawSourceItemDetail;

function event(input: Omit<DemoSeedItem, "status" | "itemType" | "city" | "publishedAt">): DemoSeedItem {
  return {
    ...input,
    city: "上海",
    publishedAt: "2026-06-13T10:00:00.000+08:00",
    status: "new",
    itemType: "event"
  };
}

function venue(input: Omit<DemoSeedItem, "status" | "itemType" | "city" | "publishedAt">): DemoSeedItem {
  return {
    ...input,
    city: "上海",
    publishedAt: "2026-06-13T10:00:00.000+08:00",
    status: "new",
    itemType: "venue"
  };
}

function signal(source: string, label: string, score: number, evidence: string) {
  return [
    {
      source,
      label,
      score,
      evidence
    }
  ];
}

export const demoSeedCatalog: DemoSeedItem[] = [
  event({
    id: "seed-xuhui-film-night",
    source: "douban",
    sourceId: "douban-xuhui-film-night",
    sourceUrl: "https://www.douban.com/event/seed-xuhui-film-night/",
    title: "衡山路独立影像夜",
    content: "小型放映、映后聊天和附近咖啡馆联动，适合一个人安静看完再散步。",
    author: "城市影像小组",
    area: "徐汇",
    address: "衡山路 880 号",
    lat: 31.204,
    lng: 121.446,
    startsAt: "2026-06-14T19:30:00.000+08:00",
    tags: ["电影", "咖啡", "安静", "solo"],
    trendScore: 76,
    confidence: 88,
    popularity: 62,
    quietness: 88,
    priceLevel: 2,
    sourceSignals: signal("douban", "同城想看上升", 76, "近 24 小时想看人数增长 18%")
  }),
  event({
    id: "seed-xuhui-westbund-market",
    source: "xiaohongshu",
    sourceId: "xhs-westbund-comic-market",
    sourceUrl: "https://www.xiaohongshu.com/explore/seed-westbund-comic-market",
    title: "西岸漫画与独立出版市集",
    content: "漫画摊位、独立出版、咖啡快闪和创作者签售，下午到傍晚热度最高。",
    author: "西岸活动观察",
    area: "徐汇",
    address: "龙腾大道 2555 号",
    lat: 31.184,
    lng: 121.466,
    startsAt: "2026-06-15T14:00:00.000+08:00",
    tags: ["漫画", "市集", "咖啡", "lively"],
    trendScore: 91,
    confidence: 84,
    popularity: 86,
    quietness: 42,
    priceLevel: 2,
    sourceSignals: signal("xiaohongshu", "附近讨论升温", 91, "相关笔记收藏率高于同城均值")
  }),
  venue({
    id: "seed-xuhui-wukang-book-cafe",
    source: "xiaohongshu",
    sourceId: "xhs-wukang-book-cafe",
    sourceUrl: "https://www.xiaohongshu.com/explore/seed-wukang-book-cafe",
    title: "武康路旧书咖啡",
    content: "旧书、手冲和靠窗单人座，适合低噪音下午路线。",
    author: "附近咖啡雷达",
    area: "徐汇",
    address: "武康路 376 号",
    lat: 31.213,
    lng: 121.44,
    tags: ["书店", "咖啡", "安静", "solo"],
    trendScore: 78,
    confidence: 87,
    popularity: 72,
    quietness: 86,
    priceLevel: 2,
    sourceSignals: signal("xiaohongshu", "收藏稳定", 78, "书店和咖啡标签共同出现频率高")
  }),
  venue({
    id: "seed-xuhui-park-cafe",
    source: "amap-poi",
    sourceId: "amap-xujiahui-park-cafe",
    sourceUrl: "https://ditu.amap.com/place/seed-xujiahui-park-cafe",
    title: "徐家汇公园玻璃咖啡亭",
    content: "靠近公园步道，适合低预算短暂停留和步行路线。",
    area: "徐汇",
    address: "肇嘉浜路 889 号",
    lat: 31.195,
    lng: 121.442,
    tags: ["咖啡", "公园", "低预算", "walking"],
    trendScore: 67,
    confidence: 82,
    popularity: 61,
    quietness: 76,
    priceLevel: 1,
    sourceSignals: signal("amap-poi", "POI 周边热度", 67, "公园和咖啡 POI 组合适合短路线")
  }),
  event({
    id: "seed-xuhui-long-museum-night",
    source: "bilibili",
    sourceId: "bili-long-museum-night",
    sourceUrl: "https://www.bilibili.com/video/seed-long-museum-night",
    title: "龙美术馆夜场导览",
    content: "艺术博主发布夜场动线，适合展览、拍照和滨江散步。",
    author: "看展切片 Bot",
    area: "徐汇",
    address: "龙腾大道 3398 号",
    lat: 31.184,
    lng: 121.462,
    startsAt: "2026-06-19T18:00:00.000+08:00",
    tags: ["展览", "艺术", "滨江", "date"],
    trendScore: 82,
    confidence: 81,
    popularity: 77,
    quietness: 58,
    priceLevel: 3,
    sourceSignals: signal("bilibili", "看展视频播放走高", 82, "夜场导览切片播放增长明显")
  }),
  event({
    id: "seed-jingan-coffee-festival",
    source: "xiaohongshu",
    sourceId: "xhs-jingan-coffee-festival",
    sourceUrl: "https://www.xiaohongshu.com/explore/seed-jingan-coffee-festival",
    title: "静安咖啡文化节打卡线",
    content: "静安寺周边咖啡摊位、品牌展和短路线攻略热度上升。",
    author: "静安咖啡观察",
    area: "静安",
    address: "南京西路 1601 号",
    lat: 31.224,
    lng: 121.445,
    startsAt: "2026-06-13T11:00:00.000+08:00",
    tags: ["咖啡", "市集", "展览", "lively"],
    trendScore: 94,
    confidence: 88,
    popularity: 91,
    quietness: 34,
    priceLevel: 2,
    sourceSignals: signal("xiaohongshu", "同城笔记爆发", 94, "静安寺咖啡关键词收藏和评论同步上升")
  }),
  event({
    id: "seed-jingan-yuyuan-theatre",
    source: "douban",
    sourceId: "douban-yuyuan-theatre",
    sourceUrl: "https://www.douban.com/event/seed-yuyuan-theatre/",
    title: "愚园路小剧场即兴夜",
    content: "小剧场、即兴喜剧和附近酒馆联动，适合轻松约会。",
    author: "小剧场同城",
    area: "静安",
    address: "愚园路 300 号",
    lat: 31.226,
    lng: 121.447,
    startsAt: "2026-06-14T20:00:00.000+08:00",
    tags: ["戏剧", "夜生活", "约会", "lively"],
    trendScore: 79,
    confidence: 83,
    popularity: 74,
    quietness: 38,
    priceLevel: 2,
    sourceSignals: signal("douban", "报名热度上升", 79, "近两日想参加人数持续增加")
  }),
  venue({
    id: "seed-jingan-rooftop-bookstore",
    source: "amap-poi",
    sourceId: "amap-jingan-rooftop-bookstore",
    sourceUrl: "https://ditu.amap.com/place/seed-jingan-rooftop-bookstore",
    title: "静安寺屋顶书店",
    content: "屋顶座位、展架和轻食，适合安静阅读与短暂停留。",
    area: "静安",
    address: "南京西路 1618 号",
    lat: 31.225,
    lng: 121.446,
    tags: ["书店", "轻食", "安静", "solo"],
    trendScore: 73,
    confidence: 84,
    popularity: 68,
    quietness: 82,
    priceLevel: 2,
    sourceSignals: signal("amap-poi", "商圈 POI 评分稳定", 73, "书店和轻食 POI 在静安商圈保持高评分")
  }),
  venue({
    id: "seed-jingan-julu-bakery",
    source: "xiaohongshu",
    sourceId: "xhs-julu-bakery",
    sourceUrl: "https://www.xiaohongshu.com/explore/seed-julu-bakery",
    title: "巨鹿路深夜面包房",
    content: "低预算、短停留、适合随机探索的深夜补给点。",
    author: "夜间补给观察",
    area: "静安",
    address: "巨鹿路 758 号",
    lat: 31.222,
    lng: 121.458,
    tags: ["面包", "夜生活", "低预算", "random"],
    trendScore: 64,
    confidence: 80,
    popularity: 58,
    quietness: 63,
    priceLevel: 1,
    sourceSignals: signal("xiaohongshu", "夜间路线收藏", 64, "夜间补给点在周末路线中被反复提及")
  }),
  event({
    id: "seed-jingan-gallery-night",
    source: "trends-hub",
    sourceId: "trends-jingan-gallery-night",
    sourceUrl: "https://www.thepaper.cn/newsDetail_forward_seed-jingan-gallery",
    title: "胶囊画廊夜间展",
    content: "小型当代艺术展，离地铁近，适合工作日下班后短路线。",
    area: "静安",
    address: "陕西北路 600 号",
    lat: 31.23,
    lng: 121.452,
    startsAt: "2026-06-18T19:00:00.000+08:00",
    tags: ["展览", "艺术", "安静", "solo"],
    trendScore: 68,
    confidence: 82,
    popularity: 54,
    quietness: 81,
    priceLevel: 2,
    sourceSignals: signal("trends-hub", "区域艺术热度", 68, "静安展览标签近期持续出现")
  }),
  event({
    id: "seed-changning-yuyintang",
    source: "bilibili",
    sourceId: "bili-yuyintang-livehouse",
    sourceUrl: "https://www.bilibili.com/video/seed-yuyintang-livehouse",
    title: "育音堂今晚独立乐队拼盘",
    content: "三组新乐队轮番演出，适合想要热闹但不想去大场馆的人。",
    author: "演出切片 Bot",
    area: "长宁",
    address: "凯旋路 851 号",
    lat: 31.216,
    lng: 121.424,
    startsAt: "2026-06-12T20:30:00.000+08:00",
    tags: ["独立音乐", "livehouse", "夜生活", "lively"],
    trendScore: 83,
    confidence: 79,
    popularity: 81,
    quietness: 28,
    priceLevel: 3,
    sourceSignals: signal("bilibili", "演出切片播放走高", 83, "乐队关键词播放增长明显")
  }),
  venue({
    id: "seed-changning-bookstore-cafe",
    source: "xiaohongshu",
    sourceId: "xhs-changning-bookstore-cafe",
    sourceUrl: "https://www.xiaohongshu.com/explore/seed-bookstore-cafe",
    title: "上生新所屋顶书店咖啡",
    content: "适合傍晚阅读、轻食和短距离约会，周五人流中等。",
    author: "附近咖啡雷达",
    area: "长宁",
    address: "延安西路 1262 号",
    lat: 31.211,
    lng: 121.431,
    tags: ["书店", "咖啡", "约会", "安静"],
    trendScore: 72,
    confidence: 86,
    popularity: 66,
    quietness: 74,
    priceLevel: 2,
    sourceSignals: signal("xiaohongshu", "周边收藏稳定", 72, "咖啡和书店标签共同出现频率高")
  }),
  event({
    id: "seed-changning-podcast-salon",
    source: "douban",
    sourceId: "douban-podcast-salon",
    sourceUrl: "https://www.douban.com/event/seed-podcast-salon/",
    title: "愚园路播客录制沙龙",
    content: "小规模现场录制、听众交流和附近小酒馆续摊。",
    author: "播客同城",
    area: "长宁",
    address: "愚园路 1107 号",
    lat: 31.218,
    lng: 121.428,
    startsAt: "2026-06-16T19:30:00.000+08:00",
    tags: ["播客", "社交", "夜生活", "medium"],
    trendScore: 71,
    confidence: 78,
    popularity: 69,
    quietness: 49,
    priceLevel: 2,
    sourceSignals: signal("douban", "同城报名增长", 71, "播客主题小组讨论增加")
  }),
  venue({
    id: "seed-changning-park-teahouse",
    source: "amap-poi",
    sourceId: "amap-zhongshan-park-teahouse",
    sourceUrl: "https://ditu.amap.com/place/seed-zhongshan-park-teahouse",
    title: "中山公园轻食花房",
    content: "公园边花房座位，适合低预算下午茶和步行路线。",
    area: "长宁",
    address: "长宁路 780 号",
    lat: 31.223,
    lng: 121.417,
    tags: ["公园", "轻食", "低预算", "安静"],
    trendScore: 66,
    confidence: 81,
    popularity: 63,
    quietness: 79,
    priceLevel: 1,
    sourceSignals: signal("amap-poi", "步行可达性高", 66, "临近地铁和公园入口")
  }),
  event({
    id: "seed-huangpu-sinan-literature",
    source: "douban",
    sourceId: "douban-sinan-literature-night",
    sourceUrl: "https://www.douban.com/event/seed-sinan-literature/",
    title: "思南文学夜读",
    content: "作家对谈、夜间朗读和街区散步，适合安静但有内容密度的晚上。",
    author: "文学同城",
    area: "黄浦",
    address: "复兴中路 505 号",
    lat: 31.216,
    lng: 121.47,
    startsAt: "2026-06-20T19:00:00.000+08:00",
    tags: ["文学", "安静", "夜生活", "solo"],
    trendScore: 77,
    confidence: 86,
    popularity: 65,
    quietness: 84,
    priceLevel: 2,
    sourceSignals: signal("douban", "想参加稳定", 77, "文学同城活动收藏稳定")
  }),
  venue({
    id: "seed-huangpu-bund-bar",
    source: "amap-poi",
    sourceId: "amap-bund-source-bar",
    sourceUrl: "https://ditu.amap.com/place/seed-bund-source-bar",
    title: "外滩源安静酒馆",
    content: "低照度、小桌距和轻爵士，适合约会或独处放空。",
    area: "黄浦",
    address: "圆明园路 133 号",
    lat: 31.239,
    lng: 121.488,
    tags: ["酒馆", "约会", "安静", "high"],
    trendScore: 74,
    confidence: 83,
    popularity: 70,
    quietness: 76,
    priceLevel: 3,
    sourceSignals: signal("amap-poi", "商圈评分高", 74, "外滩源夜间 POI 评价稳定")
  }),
  event({
    id: "seed-huangpu-xintiandi-popup",
    source: "xiaohongshu",
    sourceId: "xhs-xintiandi-popup",
    sourceUrl: "https://www.xiaohongshu.com/explore/seed-xintiandi-popup",
    title: "新天地品牌快闪展",
    content: "互动装置、限定周边和拍照动线，适合热闹约会路线。",
    author: "快闪情报局",
    area: "黄浦",
    address: "马当路 245 号",
    lat: 31.219,
    lng: 121.476,
    startsAt: "2026-06-15T13:00:00.000+08:00",
    tags: ["展览", "快闪", "约会", "lively"],
    trendScore: 88,
    confidence: 82,
    popularity: 84,
    quietness: 31,
    priceLevel: 2,
    sourceSignals: signal("xiaohongshu", "打卡热度", 88, "快闪展笔记发布密度高")
  }),
  venue({
    id: "seed-huangpu-yuyuan-tea",
    source: "xiaohongshu",
    sourceId: "xhs-yuyuan-tea-coffee",
    sourceUrl: "https://www.xiaohongshu.com/explore/seed-yuyuan-tea",
    title: "豫园茶咖小院",
    content: "茶饮、点心和老城厢步行路线，适合低预算随机探索。",
    author: "老城厢路线",
    area: "黄浦",
    address: "方浜中路 265 号",
    lat: 31.229,
    lng: 121.492,
    tags: ["茶", "咖啡", "低预算", "random"],
    trendScore: 69,
    confidence: 80,
    popularity: 65,
    quietness: 58,
    priceLevel: 1,
    sourceSignals: signal("xiaohongshu", "老城厢收藏", 69, "茶咖和步行路线共同出现")
  }),
  event({
    id: "seed-pudong-qiantan-music",
    source: "bilibili",
    sourceId: "bili-qiantan-openair",
    sourceUrl: "https://www.bilibili.com/video/seed-qiantan-openair",
    title: "前滩户外音乐周末",
    content: "草地舞台、独立乐队和轻食车，适合热闹周末。",
    author: "城市演出切片",
    area: "浦东",
    address: "前滩休闲公园",
    lat: 31.153,
    lng: 121.489,
    startsAt: "2026-06-21T16:00:00.000+08:00",
    tags: ["独立音乐", "公园", "周末", "lively"],
    trendScore: 84,
    confidence: 80,
    popularity: 82,
    quietness: 36,
    priceLevel: 2,
    sourceSignals: signal("bilibili", "现场视频热度", 84, "前滩音乐周末视频播放上升")
  }),
  venue({
    id: "seed-pudong-riverside-cafe",
    source: "amap-poi",
    sourceId: "amap-lujiazui-riverside-cafe",
    sourceUrl: "https://ditu.amap.com/place/seed-lujiazui-riverside-cafe",
    title: "陆家嘴滨江咖啡",
    content: "滨江步道旁，可看日落，适合约会和短途步行。",
    area: "浦东",
    address: "滨江大道 1777 号",
    lat: 31.238,
    lng: 121.503,
    tags: ["咖啡", "滨江", "约会", "walking"],
    trendScore: 75,
    confidence: 84,
    popularity: 73,
    quietness: 57,
    priceLevel: 2,
    sourceSignals: signal("amap-poi", "滨江 POI 热度", 75, "日落时段步行路线评分高")
  }),
  event({
    id: "seed-pudong-art-museum-night",
    source: "xiaohongshu",
    sourceId: "xhs-pudong-art-museum-night",
    sourceUrl: "https://www.xiaohongshu.com/explore/seed-pudong-art-night",
    title: "浦东美术馆夜场",
    content: "大型展览夜场、江景动线和轻餐联动，适合中高预算约会。",
    author: "看展路线观察",
    area: "浦东",
    address: "滨江大道 2777 号",
    lat: 31.241,
    lng: 121.5,
    startsAt: "2026-06-18T18:30:00.000+08:00",
    tags: ["展览", "艺术", "约会", "high"],
    trendScore: 86,
    confidence: 85,
    popularity: 83,
    quietness: 52,
    priceLevel: 3,
    sourceSignals: signal("xiaohongshu", "看展笔记热度", 86, "夜场和江景标签收藏上升")
  }),
  venue({
    id: "seed-pudong-century-park-reading",
    source: "douban",
    sourceId: "douban-century-park-reading",
    sourceUrl: "https://www.douban.com/event/seed-century-park-reading/",
    title: "世纪公园周末阅读摊",
    content: "二手书、独立杂志和草地阅读，适合安静低预算周末。",
    author: "城市阅读小组",
    area: "浦东",
    address: "锦绣路 1001 号",
    lat: 31.216,
    lng: 121.551,
    tags: ["书店", "公园", "低预算", "安静"],
    trendScore: 70,
    confidence: 82,
    popularity: 64,
    quietness: 83,
    priceLevel: 1,
    sourceSignals: signal("douban", "小组讨论稳定", 70, "周末阅读和二手书标签持续出现")
  })
];
